import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;

public class FindDialog extends javax.swing.JDialog {
  FindDialogListener listener;

  /**
   * Creates new form FindDialog
   *
   * @param parent
   * @param modal
   */
  public FindDialog(Editor parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.listener = parent;

    keyWord.addCaretListener((CaretEvent e) -> {
       btnFind.setEnabled(!keyWord.getText().isEmpty());
    });
  }

  interface FindDialogListener {
    public void findWord(String s);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    keyWord = new javax.swing.JTextField();
    btnFind = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Key word:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.ipadx = 17;
    gridBagConstraints.ipady = 13;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 127;
    gridBagConstraints.ipady = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(keyWord, gridBagConstraints);

    btnFind.setText("Find next");
    btnFind.setEnabled(false);
    btnFind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFindActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
    getContentPane().add(btnFind, gridBagConstraints);

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.ipadx = 12;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
    getContentPane().add(btnCancel, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
    String s = keyWord.getText();
    if (!s.isEmpty()) {
      try {
        listener.findWord(s);
      } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e.getMessage());
      }
    }
  }//GEN-LAST:event_btnFindActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    dispose();
  }//GEN-LAST:event_btnCancelActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnFind;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField keyWord;
  // End of variables declaration//GEN-END:variables
}
