import java.awt.Font;
import java.awt.GraphicsEnvironment;

public class FontChooserDialog extends javax.swing.JDialog {

  FontChooserDialogListener listener;
  private Font font;
  private String fontName;
  int fontStyle = Font.PLAIN;
  int fontSize = 15;

  interface FontChooserDialogListener {
    public Font getFont();
    public void changeFont(Font f);
  }

  /**
   * Creates new form FontChooserDialog
   *
   * @param parent
   * @param modal
   */
  public FontChooserDialog(Editor parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.listener = parent;
    this.setSize(350, 200);
    loadFonts();
    loadSize();
    cbSize.setSelectedItem(listener.getFont().getSize() + "");
    switch (listener.getFont().getStyle()) {
      case 0:
        cbFontStyle.setSelectedItem("Plain");
        break;
      case 1:
        cbFontStyle.setSelectedItem("Bold");
        break;
      case 2:
        cbFontStyle.setSelectedItem("Italic");
        break;
    }
    cbFont.setSelectedItem(listener.getFont().getFontName());
  }

  private void loadSize() {
    this.cbSize.removeAllItems();
    for (int i = 0; i < 100; i++) {
      cbSize.addItem(i + "");
    }
  }

  private void loadFonts() {
    GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
    Font[] fonts = env.getAllFonts();
    this.cbFont.removeAllItems();
    String fName;
    for (Font f : fonts) {
      fName = f.getFontName();
      this.cbFont.addItem(fName);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    cbFont = new javax.swing.JComboBox<>();
    btnOK = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    cbFontStyle = new javax.swing.JComboBox<>();
    cbSize = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    cbFont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.ipadx = 60;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(cbFont, gridBagConstraints);

    btnOK.setText("OK");
    btnOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOKActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.ipadx = 27;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 33, 11, 0);
    getContentPane().add(btnOK, gridBagConstraints);

    jLabel1.setText("Font :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(jLabel1, gridBagConstraints);

    jLabel2.setText("Size :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(jLabel2, gridBagConstraints);

    jLabel3.setText("Style : ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(jLabel3, gridBagConstraints);

    cbFontStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bold", "Italic", "Plain" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.ipadx = 67;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(cbFontStyle, gridBagConstraints);

    cbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 20, 11, 0);
    getContentPane().add(cbSize, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    switch (((String) cbFontStyle.getSelectedItem()).toLowerCase()) {
      case "plain":
        fontStyle = Font.PLAIN;
        break;
      case "bold":
        fontStyle = Font.BOLD;
        break;
      case "italic":
        fontStyle = Font.ITALIC;
        break;
    }
    fontSize = Integer.parseInt((String) cbSize.getSelectedItem());
    font = new Font(fontName, fontStyle, fontSize);
    listener.changeFont(font);
    dispose();
  }//GEN-LAST:event_btnOKActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOK;
  private javax.swing.JComboBox<String> cbFont;
  private javax.swing.JComboBox<String> cbFontStyle;
  private javax.swing.JComboBox<String> cbSize;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
