import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ReplaceDialog extends javax.swing.JDialog {
  private ReplaceDialogListener listener;

  interface ReplaceDialogListener {
    public void replaceWord(String s1, String s2, String s3);
  }

  public ReplaceDialog(Editor parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.listener = parent;
    
    btnFind.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String s1 = "a";
        String s2 = txt1.getText();
        listener.replaceWord(s1, s2, "");
      }
    });
    
    btnReplace.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String s1 = "b";
        String s2 = txt1.getText();
        String s3 = txt2.getText();
        listener.replaceWord(s1, s2, s3);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txt1 = new javax.swing.JTextField();
    txt2 = new javax.swing.JTextField();
    btnReplace = new javax.swing.JButton();
    btnFind = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    btnReplace.setText("Replace");

    btnFind.setText("Find next");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txt1)
          .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnReplace)
          .addComponent(btnFind))
        .addContainerGap(136, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(93, 93, 93)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnFind))
        .addGap(44, 44, 44)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnReplace)
          .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(117, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnFind;
  private javax.swing.JButton btnReplace;
  private javax.swing.JTextField txt1;
  private javax.swing.JTextField txt2;
  // End of variables declaration//GEN-END:variables
}
